version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: twitch-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitch
      MYSQL_USER: twitchuser
      MYSQL_PASSWORD: twitchpass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitch-analytics
    working_dir: /analytics
    volumes:
      - .:/analytics
    depends_on:
      - db
